spring:
  datasource:
    url: jdbc:mysql://PROD_DB_URL?useSSL=true&serverTimezone=UTC
    username: PROD_USER
    password: PROD_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
